import numpy as np
print("--- Creating 4D Array ---")
arr_4d = np.arange(1, 37).reshape(2, 2, 3, 3)
print("Original 4D Array:\n", arr_4d)
print("\nArray Shape:", arr_4d.shape)
print("Number of Dimensions:", arr_4d.ndim)
print("-" * 50)
print("\nOperation 1: Element-wise Addition (arr_4d + 10)")
op1_result = arr_4d + 10
print(op1_result)
print("-" * 50)
print("\nOperation 2: Total Sum of all elements")
total_sum = np.sum(arr_4d)
print("Sum:", total_sum)
print("-" * 50)
print("\nOperation 3: Mean along the last axis (axis=3)")
mean_axis3 = np.mean(arr_4d, axis=3)
print(mean_axis3)
print("Resulting Shape:", mean_axis3.shape)
print("-" * 50)
print("\nOperation 4: Slicing (First block, first sub-matrix, all rows, first column)")
sliced_arr = arr_4d[0, 0, :, 0]
print("Sliced Piece:", sliced_arr)
print("-" * 50)
print("\nOperation 5: Reshaping 4D array to 2D matrix (6x6)")
reshaped_2d = arr_4d.reshape(6, 6)
print(reshaped_2d)
print("New Shape:", reshaped_2d.shape)
print("-" * 50)
print("\nOperation 6: Transposing the Array (Reversing Axes)")
transposed_arr = np.transpose(arr_4d, (3, 2, 1, 0))
print("Transposed Array Shape:", transposed_arr.shape)
print("-" * 50)
