import numpy as np
data = np.array([12, 45, 7, 23, 56, 89, 34, 11, 67, 90])
print("Original Array:", data)
min_val = np.min(data)
max_val = np.max(data)
mean_val = np.mean(data)
median_val = np.median(data)
std_dev = np.std(data)
variance = np.var(data)
print(f"Minimum Value:      {min_val}")
print(f"Maximum Value:      {max_val}")
print(f"Mean (Average):     {mean_val}")
print(f"Median:             {median_val}")
print(f"Standard Deviation: {std_dev:.2f}")
print(f"Variance:           {variance:.2f}")
